import type { ConvertContent } from './types';

// Translated convert-page content bundles, keyed by routing locale.
// English is the source and lives in src/lib/content.ts. The per-locale JSON
// files in this folder are generated by translating the English bundle; they
// are wired in here as they become available.
import de from './de.json';
import fr from './fr.json';
import es from './es.json';
import pt from './pt.json';
import it from './it.json';
import pl from './pl.json';
import se from './se.json';
import ua from './ua.json';
import cz from './cz.json';
import el from './el.json';

export const localeBundles: Record<string, ConvertContent> = {
  de, fr, es, pt, it, pl, se, ua, cz, el,
};
